// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh0fC04K0d5ASuWQ5cA9aXVNec6Xwphkc',
    appId: '1:1023506336504:web:57668058a8c98f1bec090d',
    messagingSenderId: '1023506336504',
    projectId: 'campus-lost-found-83347',
    authDomain: 'campus-lost-found-83347.firebaseapp.com',
    storageBucket: 'campus-lost-found-83347.firebasestorage.app',
    measurementId: 'G-60NXB5BQE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3YAVBYYrNk3CcnloGo3cAhWUQcExKwc',
    appId: '1:1023506336504:android:f79eb86ff050d706ec090d',
    messagingSenderId: '1023506336504',
    projectId: 'campus-lost-found-83347',
    storageBucket: 'campus-lost-found-83347.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzi4v6nsk2GFUq-5ckX-Krht2mCPuF3rc',
    appId: '1:1023506336504:ios:15e9e0197ce0136dec090d',
    messagingSenderId: '1023506336504',
    projectId: 'campus-lost-found-83347',
    storageBucket: 'campus-lost-found-83347.firebasestorage.app',
    iosBundleId: 'com.example.campusLostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzi4v6nsk2GFUq-5ckX-Krht2mCPuF3rc',
    appId: '1:1023506336504:ios:15e9e0197ce0136dec090d',
    messagingSenderId: '1023506336504',
    projectId: 'campus-lost-found-83347',
    storageBucket: 'campus-lost-found-83347.firebasestorage.app',
    iosBundleId: 'com.example.campusLostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh0fC04K0d5ASuWQ5cA9aXVNec6Xwphkc',
    appId: '1:1023506336504:web:da2d45daec95ab2bec090d',
    messagingSenderId: '1023506336504',
    projectId: 'campus-lost-found-83347',
    authDomain: 'campus-lost-found-83347.firebaseapp.com',
    storageBucket: 'campus-lost-found-83347.firebasestorage.app',
    measurementId: 'G-KYJ25WP4RC',
  );
}
